// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hojwejkjwulhhgyygocs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhvandlamtqd3VsaGhneXlnb2NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA1OTIzOTAsImV4cCI6MjA2NjE2ODM5MH0.G2kFYn28C1230j_DYqgZnpQvqARY4J7dea3f9HJdOeI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});